pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge

  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}

  - name: delete head branch after merge
    conditions:
      - base=master
      - label!=work-in-progress
    actions:
      delete_head_branch: {}
